# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Trackify-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trackify-iOS

# add pods for desired Firebase products
pod 'Firebase/Auth'

end
