# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/158U3M0t3Mk2FgbkurN2wfMP6ZZqO-vJe
"""

pip install tiny-tokenizer

pip install flair

import pandas as pd
import gzip
import json


def parse(path):
  g = gzip.open(path, 'rb')
  for l in g:
    yield json.loads(l)

def getDF(path):
  i = 0
  df = {}
  for d in parse(path):
    df[i] = d
    i += 1
  return pd.DataFrame.from_dict(df, orient='index')

df = getDF('AMAZON_FASHION_5.json.gz')


import flair
import csv 
with open('innovators.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["ProductId", "ReviewText", "Clssification","Prediction"])
    flair_sentiment = flair.models.TextClassifier.load('en-sentiment')
    for index, row in df.iterrows():
      # print(row["asin"], row['reviewText'])
      
      s = flair.data.Sentence(str(row['reviewText']))
      flair_sentiment.predict(s)
      total_sentiment = s.labels
      a,b=str.split(str(total_sentiment[0]))
      b=str(b)
      b=b[1:6]
      print(str(row['asin']),str(row['reviewText']), str(a),str(b))
      
      writer.writerow([str(row['asin']),str(row['reviewText']), str(a),str(b)])

